create database my_project;
use my_project;
select * from sales;
#1. What is the total sales revenue generated by each store?Stock_On_Hand
select st.store_Name , sum(p.product_price* s.units) as total_revenue from sales s
join products_products p on s.Product_ID = p.Product_ID
join stores_stores st on s.Store_ID = st.Store_ID
group by st.Store_Name
order by total_revenue desc;

# 2. Which products are the top-selling in terms of units sold?
select s.Product_ID, sum(s.Units) as top_selling from sales s 
join products_products p on p.Product_ID = s.Product_ID
group by s.Product_ID
order by top_selling desc
limit 5;

# 3. What is the sales performance by product category?
select p.Product_Category, sum(s.units) as total_units_sold,
sum(s.Units*p.Product_Price) as total_revnue from sales s
join products_products p  on s.Product_ID = p.Product_ID
group by p.Product_Category
order by total_revnue desc;

# 4. What are the current inventory levels for each product at each store?
SELECT st.Store_ID, p.Product_Name, i.Stock_On_Hand AS current_inventory
FROM inventory_inventory i
left JOIN stores_stores st ON i.Store_ID = st.Store_ID
left JOIN products_products p ON i.Product_ID = p.Product_ID
ORDER BY  p.Product_Name;

#5.How do monthly sales trends vary across different stores?
select st.Store_Name, date_format(s.Date,'%Y-%m') as sales_month, sum(p.product_price * s.units)
 as total_revenue from  sales s
join stores_stores st on s.Sale_ID = st.Store_ID
join products_products p on s.Product_ID = p.Product_ID
group by st.Store_Name, sales_month
 order by total_revenue desc;

#6.Which stores have the highest and lowest sales performance?
select st.Store_Name,sum(s.Units * p. Product_Price) as total_rev from sales s
join stores_stores st on s.Sale_ID = st.Store_ID
join products_products p on s.Product_ID = p.Product_ID
group by st.Store_Name
order by total_rev desc;

# 7. What is the profit margin for each product?
	select p.Product_Name ,(((p.Product_Price - p. Product_Cost) /p.Product_Price)  *100 ) as profit_margin
	from products_products p;

# 8.How are sales distributed across different cities?
select st.Store_City, sum(s.units * p.Product_Price) as Total_revnue from sales s
join stores_stores st on s.Store_ID = st.Store_ID
join products_products p on s.Product_ID = p.Product_ID
group by st.Store_City
order by Total_revnue desc;

# 9.Which products are out of stock in each store?
select st.Store_Name, p.product_Name,i.Stock_On_Hand from inventory_inventory i
left join stores_stores st on st.Store_ID = i.Store_ID
left join  products_products p on p.Product_ID = i.Product_ID
where i.Stock_On_Hand =0;

# 10.How do sales vary by specific dates?
select s.Date ,sum(s.units* p.Product_Price) as Total_Revnue from sales s
join products_products p on p.Product_ID = s.Product_ID
group by s.Date;

# 11.What is the average cost of products in each category?
SELECT p.Product_Category, AVG(p.Product_Cost) AS avg_cost
FROM products_products p
GROUP BY p.Product_Category
ORDER BY avg_cost DESC;

# 12.What is the sales growth over time for the entire company?
SELECT date_format(s.Date, '%Y-%m') AS sales_month, SUM(s.Units * p.Product_Price) AS total_revenue
FROM sales s
JOIN products_products p ON s.Product_ID = p.Product_ID
GROUP BY sales_month
ORDER BY sales_month;

# 13.How does the store open date affect sales performance?
select st.Store_Name,st.Store_Open_Date, sum(s.Units *p.Product_Price) as total_revenue from sales s
join stores_stores st on s.Store_ID = st.Store_ID
join products_products p on s.Product_ID = p.Product_ID
group by st.Store_Open_Date , st.Store_Name
order by total_revenue desc;

# 14.What percentage of total sales does each store contribute?
with total_sales as ( select sum(s.Units * p.Product_Price) as total_revenue from sales s
join products_products p on s.Product_ID = p.Product_ID )
select st.Store_Name,sum(s.Units* p.Product_Price)/(select total_revenue from total_sales) *100 as sales_percentage from sales s
join stores_stores st on s.Store_ID = st.Store_ID
join products_products p on s.Product_ID = s.Product_ID
group by st.Store_Name
order by sales_percentage desc ;

# 15.How do sales compare to current stock levels for each product?
select p.Product_Name,i.Stock_On_Hand as current_inventory,sum(s.Units) as total_units_sold from sales s
join products_products p on p.Product_ID = s.Product_ID
join inventory_inventory i on i.Store_ID= s.Store_ID
group by p.Product_Name ,i.Stock_On_Hand
order by total_units_sold desc;